### ISSUE TITLE
Drilldown with hidden series

### ISSUE THREAD

**Issue by pawelfus** [highslide-software/highcharts.com#3197]
Example: http://jsfiddle.net/highcharts/QnBT4/3/

Click on axis label - we get error in console. Caused by hidden series.

Edit: simplified example

**Comment by thegoatherder** [comment]
+1. I have the same problem here on a different use case.
http://jsfiddle.net/adamtsiopani/bt9gnakj/15/

**Comment by desflynn** [comment]
+1 - I'm also using it in a scenario like thegoatherder's jsfiddle.  Same error.

**Comment by thegoatherder** [comment]
Hi Torstein! Thanks for the quick patch. I downloaded the new drilldown.src.js from the master branch and used this in my jsFiddle example, but I'm still getting the same error as before.
http://jsfiddle.net/bt9gnakj/17/

**Comment by highslide-software** [comment]
@thegoatherder Your error seems to come from the fact that a line series without markers has no point graphic. The issue is reproduced in a simpler form at http://jsfiddle.net/highcharts/ogLruefw/. I fixed this with a new commit, dc0cbf27291a4cbe39ea48bbfe79b3bf56307ed9.

**Comment by thegoatherder** [comment]
@highslide-software - Torstein, thanks for that. It's working perfectly now. The issue can be closed I think. Do you have any indication on when this might be released to the CDN http://code.highcharts.com/stock/modules/drilldown.js ?

**Comment by highslide-software** [comment]
The new release should be out within some weeks.

**Comment by ChartFacetTeam** [comment]
Hello, this bug is still visible with last Highcharts version (http://jsfiddle.net/bd6j4fc3/). Do you have an update on it ? Thank you.

**Comment by sebastianbochan** [comment]
Hi @ChartFacetTeam,
I was not able to reproduce the problem when click on a label. Could you describe steps which I should do?

**Comment by ChartFacetTeam** [comment]
Hello @sebastianbochan , thanks for your reply.
Scenario is the following:
- Click on "Cat1"
- The chart is drilled (OK) but Serie2 is no more visible in legend so values cannot be displayed in below level.

I've attached a gif with scenario:
![2020-03-03_10-20-33](https://user-images.githubusercontent.com/61704932/75761069-b259c200-5d38-11ea-9d16-627b283ff169.gif)

Thank you !

**Comment by sebastianbochan** [comment]
The issue is different than the main case, so I created the new case here: https://github.com/highcharts/highcharts/issues/13057
